"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wesai (https://sketchfab.com/Wesai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-firered-players-room-b23b6b253207463c97db2a7092adff74
Title: Pokemon FireRed - Player's Room
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RoomModel(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.base_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tiles_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Computer_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TV_stand_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TV_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carpet_A_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carpet_B_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bed_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dresser_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bookShelf_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NES_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.railing_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stairs_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall_picture_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ambient_occlusion_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.title_fireRed_material_0.geometry}
        material={materials.fireRed_material}
      />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
